# Generated by Django 5.1.4 on 2025-02-05 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CertificateMaster',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the certificate', max_length=255)),
                ('design', models.TextField(blank=True, help_text='Design of the certificate', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('state', models.BooleanField(default=True, help_text='State of the certificate master (active/inactive)')),
                ('created_by', models.ForeignKey(help_text='User who created the certificate master', on_delete=django.db.models.deletion.CASCADE, related_name='created_certificate_masters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the course', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for the course', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the course', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the course', max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency of the price', max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Indicates if the course is paid or not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('enroll_start_date', models.DateField(blank=True, help_text='Enrollment start date', null=True)),
                ('enroll_end_date', models.DateField(blank=True, help_text='Enrollment end date', null=True)),
                ('completion_days', models.IntegerField(blank=True, help_text='Number of days to complete the course', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('state', models.BooleanField(default=True, help_text='State of the course (active/inactive)')),
                ('created_by', models.ForeignKey(help_text='User who created the course', on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('issue_date', models.DateField(help_text='Issue date of the certificate')),
                ('eol_date', models.DateField(blank=True, help_text='End of life date of the certificate', null=True)),
                ('certificate_url', models.CharField(blank=True, help_text='URL of the certificate', max_length=255, null=True)),
                ('state', models.BooleanField(default=True, help_text='State of the certificate (active/inactive)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('created_by', models.ForeignKey(help_text='User who created the certificate', on_delete=django.db.models.deletion.CASCADE, related_name='created_certificates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who received the certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course this certificate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp of enrollment')),
                ('target_end_date', models.DateField(blank=True, help_text='Target end date for the enrollment', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates if the enrollment is completed')),
                ('completion_date', models.DateField(blank=True, help_text='Date of completion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('state', models.BooleanField(default=True, help_text='State of the enrollment (active/inactive)')),
                ('course', models.ForeignKey(help_text='Course this enrollment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('created_by', models.ForeignKey(help_text='User who created the enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who enrolled in the course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
