# Generated by Django 5.1.4 on 2025-05-11 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 25), help_text='for certificates', null=True),
        ),
    ]
