# Generated by Django 5.1.4 on 2025-09-22 10:42

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='img/course/default.png', null=True, upload_to=courses.models.course_image_path),
        ),
    ]
