# Generated by Django 5.1.4 on 2025-09-22 10:51

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='img/course/default.png', help_text='Upload course image', null=True, upload_to=courses.models.course_image_path),
        ),
    ]
