# Generated by Django 5.1.4 on 2026-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon used during enrollment', max_length=50, null=True),
        ),
    ]
