---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1500
        exclude: '(alembic|static/fonts)/.*'
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: '(alembic|static)/.*'
      - id: trailing-whitespace
        exclude: static/
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        args:
          - check
          - --fix
          - --exit-non-zero-on-fix
        language: python
        types_or:
          - python
          - pyi
          - jupyter
        require_serial: true
      - id: ruff-format
        name: ruff-format
        description: Run 'ruff format' for extremely fast Python formatting
        entry: ruff format --force-exclude
        language: python
        types_or:
          - python
          - pyi
          - jupyter
        args: []
        require_serial: true
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types:
          - python
        args:
          - --rcfile=pylintrc
        stages:
          - pre-commit
        exclude: ^(alembic/)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-django
        args:
          - --reformat

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
