# Generated by Django 5.1.4 on 2025-02-05 07:33

import courses.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the module', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the module', null=True)),
                ('target_end_date', models.DateField(blank=True, help_text='Target end date for the module', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date for the module', null=True)),
                ('order', courses.fields.OrderField(blank=True, help_text='Order of the module within the course')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('state', models.BooleanField(default=True, help_text='State of the module (active/inactive)')),
                ('course', models.ForeignKey(help_text='Course this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('created_by', models.ForeignKey(help_text='User who created the module', on_delete=django.db.models.deletion.CASCADE, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
                ('prerequisite_module', models.ForeignKey(blank=True, help_text='Prerequisite module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_modules', to='modules.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleTrack',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on the module')),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates if the module is completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp of completion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('state', models.BooleanField(default=True, help_text='State of the module track (active/inactive)')),
                ('module', models.ForeignKey(help_text='Module being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='module_tracks', to='modules.module')),
                ('user', models.ForeignKey(help_text='User who is tracking the module', on_delete=django.db.models.deletion.CASCADE, related_name='module_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
