# Generated by Django 5.1.4 on 2025-02-21 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprice',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='courseName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
