# Generated by Django 5.1.4 on 2025-02-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_courseprice_date_courseprice_coursename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprice',
            name='courseName',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
