# Generated by Django 5.1.4 on 2025-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_courseprice_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprice',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
