# Generated by Django 5.1.4 on 2025-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePrice',
        ),
        migrations.AddField(
            model_name='payment',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
