# Generated by Django 5.1.5 on 2025-02-10 03:53
# pylint: disable=invalid-name
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='AssessmentUpload',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('work', models.BinaryField()),
                ('filename', models.CharField(
                    default='default_filename.png', max_length=255
                )),
                ('content_type', models.CharField(
                    default='application/octet-stream', max_length=100
                )),
                ('review_score', models.IntegerField(
                    blank=True, null=True
                )),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_teacher', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='assigned_reviews',
                    to=settings.AUTH_USER_MODEL
                )),
                ('user_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='student_submissions',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompetition',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(
                    choices=[(1, 'Active'),
                    (0, 'Inactive')],
                    default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
