# Generated by Django 5.1.4 on 2025-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons_required', models.IntegerField(default=20)),
                ('course_end_date', models.DateField()),
            ],
        ),
    ]
