# Generated by Django 5.1.5 on 2025-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_student_competition_studentcompetition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcompetition',
            old_name='user_id',
            new_name='user',
        ),
    ]
