# Generated by Django 5.1.4 on 2025-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_competitiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiondetails',
            name='total_lessons_required',
            field=models.IntegerField(default=1),
        ),
    ]
