# Generated by Django 5.1.4 on 2025-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_competitiondetails_total_lessons_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentupload',
            name='work',
            field=models.CharField(max_length=255),
        ),
    ]
