# Generated by Django 5.1.5 on 2025-02-07 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentupload_review_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentupload',
            old_name='teacher',
            new_name='assigned_teacher',
        ),
        migrations.RemoveField(
            model_name='assessmentupload',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='assessmentupload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentupload',
            name='review_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentupload',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
