# Generated by Django 5.1.4 on 2025-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
