# Generated by Django 5.1.4 on 2025-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_rangoli_batch_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='level_completed',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Special', 'Special'), ('Advanced', 'Advanced'), ('Professional', 'Professional'), ('Extreme', 'Extreme')], max_length=50, null=True),
        ),
    ]
