# Generated by Django 5.1.4 on 2025-04-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_other_district_student_other_state_and_more'),
    ]

    operations = [
    ]
