# Generated by Django 5.1.4 on 2025-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_district_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='jilha',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='full_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='jilha',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pictures/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pictures/%y/%m/%d/'),
        ),
    ]
