# Generated by Django 5.1.4 on 2025-02-05 07:33

import courses.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name of the lesson', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the lesson', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('target_date', models.DateField(blank=True, help_text='Target date for the lesson', null=True)),
                ('available_date', models.DateField(blank=True, help_text='Available date for the lesson', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
                ('state', models.BooleanField(default=True, help_text='State of the lesson (active/inactive)')),
                ('order', courses.fields.OrderField(blank=True)),
                ('created_by', models.ForeignKey(help_text='User who created the lesson', on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('lesson_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(help_text='Module this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='modules.module')),
                ('prerequisite_lesson', models.ForeignKey(blank=True, help_text='Prerequisite lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_lessons', to='lessons.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonTrack',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on the lesson')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp of completion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('state', models.BooleanField(default=True, help_text='State of the lesson track (active/inactive)')),
                ('lesson', models.ForeignKey(help_text='Lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tracks', to='lessons.lesson')),
                ('user', models.ForeignKey(help_text='User who is tracking the lesson', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
