# Generated by Django 5.1.4 on 2025-03-22 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessontrack',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterField(
            model_name='lessontrack',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessontrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessontrack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lessontrack',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tracks', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='lessontrack',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lessontrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lessontrack',
            name='time_spent',
        ),
    ]
