# Generated by Django 5.1.4 on 2025-03-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessontrack_course_alter_lessontrack_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontrack',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
    ]
