# Generated by Django 5.1.4 on 2026-03-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessontrack_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='release_after_days',
            field=models.IntegerField(default=0, help_text='Days after batch start when lesson unlocks'),
        ),
    ]
