name: pre-commit

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run pre-commit on modified files
        run: pre-commit run --from-ref origin/$(git branch --show-current) --to-ref HEAD --show-diff-on-failure --color=always
        shell: bash
