name: pre-commit

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r dev-requirements.txt
      - uses: actions/setup-python@v5
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --from-ref HEAD^^^ --to-ref HEAD
        shell: bash
#    - uses: pre-commit/action@v3.0.1
