name: pre-commit

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Get list of modified and new files
        id: get_changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/$(git branch --show-current)..HEAD)
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
      - name: Run pre-commit on modified and new files
        run: |
          pre-commit run --files $(echo ${{ env.changed_files }}) --show-diff-on-failure --color=always
        shell: bash
